### ISSUE TITLE
redmine 2.3.2-setting questions and access error

### ISSUE THREAD

**Issue by fengyedou** [ochorocho/whitewall#10]
Hi, I tested on redmine 2.3.2. after installing, there is a menu: the great White Wall in the main page, but if I click it, there is such error message:You do not have the permission to access this area

and in the plug-in settings, I want to ask about these setting's meaning and what need to put in the box.

1.Graph-Limit Line
2.User-Hide User
3.System Graph-Custom field for system graph---what does it mean, and what should be selected? or need to create a new custom field?
4.classification graph-there are some defined issue fields are in the selection box, but I am not sure what to choose, what does the setting mean?

I think if there is a readme for guding to usage, that will be more easy to understand the plug-in.

**Comment by ochorocho** [comment]
no response ...
