### ISSUE TITLE
support redmine 3.3.X or higher?

### ISSUE THREAD

**Issue by archonwang** [ochorocho/whitewall#27]
support redmine 3.3.X or higher? @ochorocho

**Comment by ochorocho** [comment]
Thanks for your interest, currently working on > 3.x support.
This may take a few more days.

**Comment by ochorocho** [comment]
@archonwang master branch should work on Redmine > 3.0.0

**Comment by archonwang** [comment]
@ochorocho , Thanks so much.
but, it seems have the performancee problem. I tried to use it in my team with 20 peoples and 15 projects, it is so slow and it rendering in background so long time until time-out. 

could you have any suggestion for the problem? Thanks so much.

**Comment by ochorocho** [comment]
@archonwang what are your hardware specs?
I'm running on a 4 Core CPU / 4Ghz with 6GB ram.

**Comment by archonwang** [comment]
@ochorocho , I used 4 core cpu 3ghz with 8gb ram.

**Comment by ochorocho** [comment]
@archonwang can you optimize your mysql settings? In particular the query cache.
How many tickets are in your database?

**Comment by ochorocho** [comment]
3.3.x is now supported.

I will address the performance trouble in this ticket #30
